# Стадия сборки
FROM nginx:alpine

# Копируем уже собранные статические файлы (создаются локально скриптом деплоя)
COPY build /usr/share/nginx/html

# Копируем конфигурацию nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Открываем порт
EXPOSE 3000

# Запускаем nginx
CMD ["nginx", "-g", "daemon off;"]