server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Проксирование запросов к API - используем переменную окружения или значение по умолчанию
    location /api/ {
        # В production эти запросы будут обрабатываться внешним NGINX
        # Этот блок нужен только для локальной разработки
        try_files $uri $uri/ /index.html;
    }

    # Для React-Router - перенаправляем все запросы на index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Статические файлы
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires max;
        add_header Cache-Control "public, max-age=31536000";
    }
}
