services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5001

  postgres:
    ports:
      - "5489:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  redis:
    ports:
      - "6396:6379"
    volumes:
      - redis_data_dev:/data

volumes:
  postgres_data_dev:
  redis_data_dev:
