"""Initial migration

Revision ID: 67ac6e1c9da0
Revises:
Create Date: 2025-04-21 15:55:14.075743

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "67ac6e1c9da0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bitrix_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("company_type", sa.String(), nullable=True),
        sa.Column("uid_1c", sa.String(), nullable=True),
        sa.Column("inn", sa.String(), nullable=True),
        sa.Column("kpp", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("main_manager", sa.String(), nullable=True),
        sa.Column("last_sale_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("document_amount", sa.String(), nullable=True),
        sa.Column(
            "dynamic_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("last_synced", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_status", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_companies_bitrix_id"), "companies", ["bitrix_id"], unique=True
    )
    op.create_index(op.f("ix_companies_id"), "companies", ["id"], unique=False)
    op.create_index(op.f("ix_companies_inn"), "companies", ["inn"], unique=False)
    op.create_index(op.f("ix_companies_kpp"), "companies", ["kpp"], unique=False)
    op.create_index(op.f("ix_companies_name"), "companies", ["name"], unique=False)
    op.create_index(op.f("ix_companies_region"), "companies", ["region"], unique=False)
    op.create_index(op.f("ix_companies_uid_1c"), "companies", ["uid_1c"], unique=True)
    op.create_table(
        "contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bitrix_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("contact_type", sa.String(), nullable=True),
        sa.Column(
            "dynamic_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("last_synced", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_status", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contacts_bitrix_id"), "contacts", ["bitrix_id"], unique=True
    )
    op.create_index(op.f("ix_contacts_id"), "contacts", ["id"], unique=False)
    op.create_index(op.f("ix_contacts_name"), "contacts", ["name"], unique=False)
    op.create_table(
        "custom_sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_custom_sections_id"), "custom_sections", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_custom_sections_section_id"),
        "custom_sections",
        ["section_id"],
        unique=False,
    )
    op.create_table(
        "doctors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bitrix_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "dynamic_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("last_synced", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_status", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_doctors_bitrix_id"), "doctors", ["bitrix_id"], unique=True)
    op.create_index(op.f("ix_doctors_id"), "doctors", ["id"], unique=False)
    op.create_table(
        "field_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=True),
        sa.Column("app_field_name", sa.String(), nullable=True),
        sa.Column("bitrix_field_id", sa.String(), nullable=True),
        sa.Column("field_type", sa.String(), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column(
            "value_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_multiple", sa.Boolean(), nullable=True),
        sa.Column("entity_type_id", sa.Integer(), nullable=True),
        sa.Column("show_in_card", sa.Boolean(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_field_mappings_app_field_name"),
        "field_mappings",
        ["app_field_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_field_mappings_entity_type"),
        "field_mappings",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_field_mappings_id"), "field_mappings", ["id"], unique=False
    )
    op.create_table(
        "global_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_global_settings_id"), "global_settings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_global_settings_key"), "global_settings", ["key"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("bitrix_user_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("regions", sa.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bitrix_user_id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "company_contacts",
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("contact_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
    )
    op.create_table(
        "visits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bitrix_id", sa.Integer(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "dynamic_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("visit_type", sa.String(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("with_distributor", sa.Boolean(), nullable=True),
        sa.Column("sansus", sa.Boolean(), nullable=True),
        sa.Column("last_synced", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_status", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_visits_bitrix_id"), "visits", ["bitrix_id"], unique=True)
    op.create_index(op.f("ix_visits_id"), "visits", ["id"], unique=False)
    op.create_table(
        "visit_contacts",
        sa.Column("visit_id", sa.Integer(), nullable=True),
        sa.Column("contact_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["visit_id"],
            ["visits.id"],
        ),
    )
    op.create_table(
        "visit_doctors",
        sa.Column("visit_id", sa.Integer(), nullable=True),
        sa.Column("doctor_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["visit_id"],
            ["visits.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("visit_doctors")
    op.drop_table("visit_contacts")
    op.drop_index(op.f("ix_visits_id"), table_name="visits")
    op.drop_index(op.f("ix_visits_bitrix_id"), table_name="visits")
    op.drop_table("visits")
    op.drop_table("company_contacts")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_global_settings_key"), table_name="global_settings")
    op.drop_index(op.f("ix_global_settings_id"), table_name="global_settings")
    op.drop_table("global_settings")
    op.drop_index(op.f("ix_field_mappings_id"), table_name="field_mappings")
    op.drop_index(op.f("ix_field_mappings_entity_type"), table_name="field_mappings")
    op.drop_index(op.f("ix_field_mappings_app_field_name"), table_name="field_mappings")
    op.drop_table("field_mappings")
    op.drop_index(op.f("ix_doctors_id"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_bitrix_id"), table_name="doctors")
    op.drop_table("doctors")
    op.drop_index(op.f("ix_custom_sections_section_id"), table_name="custom_sections")
    op.drop_index(op.f("ix_custom_sections_id"), table_name="custom_sections")
    op.drop_table("custom_sections")
    op.drop_index(op.f("ix_contacts_name"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_bitrix_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_companies_uid_1c"), table_name="companies")
    op.drop_index(op.f("ix_companies_region"), table_name="companies")
    op.drop_index(op.f("ix_companies_name"), table_name="companies")
    op.drop_index(op.f("ix_companies_kpp"), table_name="companies")
    op.drop_index(op.f("ix_companies_inn"), table_name="companies")
    op.drop_index(op.f("ix_companies_id"), table_name="companies")
    op.drop_index(op.f("ix_companies_bitrix_id"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
